# Generated by Django 6.0.3 on 2026-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Descripción detallada del curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_hero',
            field=models.ImageField(blank=True, help_text='Imagen para la sección hero', null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='incluye',
            field=models.TextField(blank=True, help_text='Escribe cada item en una línea nueva'),
        ),
    ]
