# Generated by Django 6.0.3 on 2026-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_curso_descripcion_larga_curso_imagen_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('vocabulario', 'Vocabulario'), ('gramatica', 'Gramática'), ('pronunciacion', 'Pronunciación'), ('consejos', 'Consejos'), ('cultura', 'Cultura')], max_length=20)),
                ('descripcion_corta', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recursos/')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube o Vimeo')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
