# Generated by Django 6.0.3 on 2026-03-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='video_url',
        ),
    ]
